language: ruby
rvm:
  - 2.5
  - 2.6
  - ruby-head

gemfile:
  - gemfiles/rails4_2.gemfile
  - gemfiles/rails5_0.gemfile
  - gemfiles/rails5_1.gemfile
  - gemfiles/rails5_2.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem install -v 1.17.2 bundler --no-rdoc --no-ri